name: build Vue
on: push
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: hotrungnhan/VuePagesAction@1.0.1
        with:
          username: "hotrungnhan"
          reponame: "hotrungnhan"
          cname: "hotrungnhan.tk"
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          VUE_APP_KEY: ${{ secrets.VUE_APP_KEY }}
          VUE_APP_URL: ${{ secrets.VUE_APP_URL }}
